name: CI

on:
  push:
    branches: [ main, feat/** ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Validate current commit (push)
        if: github.event_name == 'push'
        run: bunx commitlint --last --verbose
      - name: Validate PR commits
        if: github.event_name == 'pull_request'
        run: bunx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Lint
        run: bun run lint
      - name: Typecheck
        run: bun run typecheck
      - name: Build
        run: bun run build
      - name: Test
        run: bun run test --silent

  codegen-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install deps
        run: bun install
      - name: Run codegen
        run: bun run codegen
      - name: Ensure nitrogen is clean
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Generated files changed. Please commit generated code." >&2
            git status
            exit 1
          fi

