name: CI

on:
  push:
    branches: [ main, feat/** ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Validate current commit (push)
        if: github.event_name == 'push'
        run: bunx commitlint --last --verbose
      - name: Validate PR commits
        if: github.event_name == 'pull_request'
        run: bunx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Lint
        run: bun run lint
      - name: Typecheck
        run: bun run typecheck
      - name: Build
        run: bun run build
      - name: Test
        run: bun run test --silent

  codegen-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install deps
        run: bun install
      - name: Run codegen (Nitro only)
        run: bunx nitro-codegen --logLevel="debug"
      - name: Ensure nitrogen is clean
        run: |
          if ! git diff --quiet -- nitrogen/generated; then
            echo "Generated files changed in nitrogen/generated. Please commit generated code." >&2
            git status --porcelain -- nitrogen/generated || true
            git diff --name-only -- nitrogen/generated || true
            exit 1
          fi

